Geo-Mafia/Geo-Mafia

player_module/player.test.js
player_module/player_class_declaration.js

Adding declaration code for Player Class (including Subclass information for Killers) as well as the unit test file to fulfill Issue #9 . Something to take note of, the test file will _need_ to be moved into the following Path position Geo-Mafia/appGeo/src/tests/player.test.js after Pull Request #14 goes through.

Adding Player Class Unit Tests

---

appGeo/src/tests/game_tests.ts

Wrote the tests for the Game Object. Created test cases for each scenario that comes up for each of the constructors and functions I could think of.

Fe playerdev

---

appGeo/src/app/game/game.component.js
appGeo/src/tests/game_tests.ts

Created the actual component file for the game class.

Wrote up a game components class

---

appGeo/karma.conf.js
appGeo/package-lock.json
appGeo/package.json
appGeo/src/app/chat/chat_class_declaration.ts
appGeo/src/app/player/player_class_declaration.js
appGeo/src/app/player/player_class_declaration.ts
appGeo/src/tests/chat.spec.ts
appGeo/src/tests/player.spec.ts

Related to Issue #36, this PR is to change Chat and Player tests to TS. Included I have also put both the .ts & .js version of the class declarations (for both Chat and Player) as I saw that the current tests passing (database) used .ts. Currently trying to see if all .ts will work, afterwards can delete the .js if it does.

Modify chat & player tests to ts

---

appGeo/package-lock.json
appGeo/src/app/game/game-rules.component.html
appGeo/src/app/game/game-rules.component.ts
appGeo/src/app/game/game.component.ts
appGeo/src/tests/game.spec.ts
appGeo/src/tests/game_rules.spec.ts

In order to implement the game timer, I have had to create a game rule class that helps keep track of scheduled events and general game conditions. Merging these in to make sure that they exist and can lay the foundation for the timer system which will be worked on next.

Added Game Rule System

---

appGeo/src/app/game/game.component.ts
appGeo/src/app/player/player.component.ts
appGeo/src/tests/chat.spec.ts
appGeo/src/tests/game.spec.ts
appGeo/src/tests/map_tests.spec.ts
appGeo/src/tests/player.spec.ts
appGeo/src/tests/snapshot.spec.ts

This is related strictly only to fix tests that are now failing becuase I moved the class declarations for Messages, Chats, and Players inside the .component files rather than the position they were in before (inside their own class declaration files)

Running tests for Players, Game, and Chats

---

appGeo/src/app/game/game-rules.component.ts
appGeo/src/tests/campus-map.spec.ts
appGeo/src/tests/game.spec.ts
appGeo/src/tests/game_rules.spec.ts

There was one small bug causing errors in the game rule, which has been fixed. A few more tests for game rules that should also be passing has been added. There were a few tests in game.spec that shouldn't be passing yet (relating to game start events, which will be implemented shortly) so I've also modified those. They should be failing currently, but that will change in the next code I push.

Fixed the Game Rule Failing Errors

---

appGeo/src/app/chat/chat.component.ts

I am just pushing this from my Fork branch to Jose's. I am going to self-merge this PR.

chat push to firebase, works

---

appGeo/src/app/chat/chat.component.html
appGeo/src/app/chat/chat.component.ts
appGeo/src/app/chat/chat.module.ts
appGeo/src/app/home/home-routing.module.ts
appGeo/src/app/home/home.module.ts

another self PR to merge my forked branch to the branch here so Jose can work with it

textfield now working

---

appGeo/src/app/app-routing.module.ts
appGeo/src/app/app.module.ts
appGeo/src/app/chat/chat.component.css
appGeo/src/app/chat/chat.component.html
appGeo/src/app/chat/chat.component.ts
appGeo/src/app/chat/chat.module.ts
appGeo/src/app/home/home-routing.module.ts
appGeo/src/app/home/home.component.html
appGeo/src/app/home/home.module.ts
appGeo/src/app/player/player.component.ts
appGeo/src/tests/chat.spec.ts

Creating the PR just so that I can run the Unit Tests.
Major note - Kyu and I decided that we would get a simplified message that only contains the timestamp of when message is sent, message content, and the name of the player who sent the message. And instead of having a Chat, we will just have an array of Messages since we are just trying to get a public chat that everyone is going to be a part of.
The more complicated Message object and Chat object have been left so that in the event we want a more fleshed out version, we could have that (reflected in Unit Tests)

Barebone working UI chats

---

appGeo/src/app/home/home-routing.module.ts
appGeo/src/app/home/home.component.html
appGeo/src/app/home/home.component.ts
appGeo/src/app/home/home.module.ts
appGeo/src/app/player/killing.component.html
appGeo/src/app/player/killing.component.ts
appGeo/src/app/player/killing.module.ts
appGeo/src/app/player/player.component.ts

UI for Killing Players is working. We just need to extract certain information:
- A list of all players nearby the Killer (probably from the Bubble object?). Even if list includes dead players or other killers, it's fine. The filters I have in place make it so only ALIVE players and Civilians are displayed as options for the killers
- The player object associated with the user (aka killer) itself. This way we can access the killPlayer function.
- Along the same lines as above, we need a way to identify if user is a killer or not. If they are, then they get access to the Killing Page. Otherwise, they do not.

Have the Killing Players UI working

---

appGeo/src/app/home/home-routing.module.ts
appGeo/src/app/home/home.component.html
appGeo/src/app/home/home.component.ts
appGeo/src/app/home/home.module.ts
appGeo/src/app/player/player.component.ts
appGeo/src/app/voting/voting.component.css
appGeo/src/app/voting/voting.component.html
appGeo/src/app/voting/voting.component.ts
appGeo/src/app/voting/voting.module.ts

Something to still keep in mind with this PR is that we still haven't hooked up the backend part of how we are drawing in the information. In and of itself however, the UI and the associated logic work. Edge cases that I tested myself:
- If Voting is **not** open, then Killers can access the killing page, while Civilians _cannot_ open the killing page
- If Voting **is** open, then Killers cannot access the killing page nor can Civilians

UI interface for voting

---

appGeo/src/app/chat/chat.component.ts
appGeo/src/app/game/game.component.ts
appGeo/src/app/home/home.component.html
appGeo/src/app/home/home.component.ts
appGeo/src/app/player/player.component.ts
appGeo/src/main.ts

Implemented a global variable that represents the actual "Player" who is running the app on the device right now. Also now Chat component can use the username retrieved from the log-in. 
Closes #77

Pulling/Pushing Player on Database

---

.github/workflows/main.yml

Made some jobs parallel, removed build process which already is done in tns run ios.
DO NOT MERGE.

Checking the new workflow which should save a bit more time

---

appGeo/src/app/home/home.component.html
appGeo/src/app/home/home.component.ts

Making it so that players have to log in first before they have access to different features.

User log in first

---

appGeo/package-lock.json
appGeo/src/app/snapshot/snapshot.component.html
appGeo/src/app/snapshot/snapshot.component.ts

Done with snapshot class implementations and snapshot UI by handling the part that interacts with the database. Ready to merge.

Snapshot class implementation and Snapshot UI

---

appGeo/src/app/game/game.component.ts
appGeo/src/app/home/home.component.ts
appGeo/src/app/player/player.component.ts

This pull requests all schedule game events. The game can also be started by setting "gameStarted" to true. This should trigger the game start in the admin player, which updates the setting for every other game object for every other user.

Game Event Running

---

appGeo/src/app/game/game.component.ts
appGeo/src/app/player/player.component.ts
appGeo/src/main.ts

Testing things out for unit tests, don't merge until passing

Fix to Unit Tests

---

appGeo/src/app/game/game.component.ts
appGeo/src/app/home/home.component.ts

I missed these in the previous PR. All this does is add the map object and game rules to the database and also added the line for the gameTick.

Fixed the lack of map object and added game tick

---

README.md
appGeo/src/app/snapshot/snapshot.component.ts

This pull request modifies the snapshot access of game map

Modified Snapshot Access of Game Map

---

appGeo/src/app/game/game.component.ts
appGeo/src/app/home/home.component.ts
appGeo/src/main.ts

global.playerlist is now accessible throughout and consistently updated.

Fixed global playerlists

---

appGeo/src/app/home/home.component.html
appGeo/src/app/home/home.component.ts

Moved code from Location component over to home component so that it can be called immediately after successful login.

Code for Location moved over to activate upon Login

---

appGeo/package-lock.json
appGeo/src/app/game/game-rules.component.ts
appGeo/src/app/game/game.component.ts
appGeo/src/app/home/home.component.ts
appGeo/src/tests/game_rules.spec.ts

This should simply reimplement the changes to the game events done after #104 so that it can be readded.

Readded all changes

---

appGeo/src/app/snapshot/snapshot.component.ts

This pull request used the playersBubble function to get the bubble that a player is in. Now the functionality of taking a snapshot and sending a snapshot to the database should be good.

Update Snapshot to have the functionality that gets the bubble a player is in

---

appGeo/src/app/home/home.component.html
appGeo/src/app/home/home.component.ts
appGeo/src/app/player/killing.component.ts

Note - This PR now also changes some things with how killing was working (there was a call to a function killPlayer and because types get destroyed, had to move over a function). This is now accurately working and we see the chance being reflected in Firebase Information! This includes killers having their remaining kills being decremented, the players being adequately being killed, and also being removed from list of future killings.

Home page has indicator if you are a Killer or Civilian

---

appGeo/src/app/admin/admin.component.html
appGeo/src/app/admin/admin.component.ts
appGeo/src/app/admin/admin.modules.ts
appGeo/src/app/game/game.component.ts
appGeo/src/app/home/home-routing.module.ts
appGeo/src/app/home/home.component.html
appGeo/src/app/home/home.component.ts
appGeo/src/app/home/home.module.ts
appGeo/src/app/services/game-data.service.ts

I've added an admin page. If a user is an admin they will be able to access this page to start and end the game.

Admin page
